# Documentation sources configuration
# This file defines all documentation sources to be ingested, chunked, and embedded

sources:
  # Website sources - crawl and extract documentation from websites
  websites:
    - name: "Toolhive Website Docs"
      url: "https://docs.stacklok.com/toolhive"
      path_prefix: "/toolhive"  # Limit crawling to this path
      enabled: true

  # GitHub repository sources - fetch markdown files from specific repos
  github_repos:
    - name: "Toolhive Repo Docs"
      repo_owner: "stacklok"
      repo_name: "toolhive"
      branch: "main"  # Optional, defaults to default branch
      paths:
        - "docs/**/*.md"  # Glob patterns for markdown files
        - "README.md"
      enabled: true

    - name: "Toolhive Studio Docs"
      repo_owner: "stacklok"
      repo_name: "toolhive-studio"
      branch: "main"  # Optional, defaults to default branch
      paths:
        - "docs/**/*.md"  # Glob patterns for markdown files
        - "README.md"
      enabled: true

# Fetching configuration (applies to all sources)
fetching:
  timeout: 30  # HTTP request timeout in seconds
  max_retries: 3  # Maximum retry attempts for failed requests
  concurrent_limit: 5  # Maximum concurrent HTTP requests
  delay_ms: 100  # Delay between requests in milliseconds
  max_depth: 5  # Maximum crawl depth for websites

# GitHub API configuration
github:
  # Optional: GitHub personal access token for higher rate limits
  # Can also be set via GITHUB_TOKEN environment variable
  token: null  # or set GITHUB_TOKEN env var
  api_url: "https://api.github.com"  # GitHub API base URL
